name: 'Post Release'
description: 'Sends a message to a Discord webhook after a release is published and/or updates the readme with the latest release information'
author: 'Minecraftschurli'
inputs:
  webhook-url:
    description: 'The webhook URL to send the message to'
    required: false
  webhook-message:
    description: 'The message to send'
    required: false
  webhook-title:
    description: 'The title of the message to send'
    required: false
  github-token:
    description: 'The GitHub token to use'
    required: false
  github-update-message:
    description: 'The message to use for the update commit'
    required: false
  github-link:
    description: 'The link to the created GitHub release'
    required: false
  modrinth-link:
    description: 'The link to the created Modrinth release'
    required: false
  curseforge-link:
    description: 'The link to the created CurseForge release'
    required: false
  exclude-links-readme:
    description: 'A comma-separated list of links to exclude from the readme'
    required: false
  exclude-links-webhook:
    description: 'A comma-separated list of links to exclude from the webhook message'
    required: false
  published-to:
    description: 'The platforms the release was published to'
    required: true
  version:
    description: 'The version of the release'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
